### PR TITLE
add persian translation

### PR DESCRIPTION
**Pull request by eshagh79**
Hi, I added the Farsi language translation, but I think one of the strings has a problem, in line 100 and for the fileSizeError key.
I don't understand what you mean here.
Are files larger than N kilobytes allowed or not?

### CODE REVIEW

**Comment by erosman** [comment]
Thank you. Please check again as the original `manifest.json` may change before the final release.
There is already a minor change and `"patterns": { "message": "Patterns" },` was added.

**Comment by eshagh79** [comment]
Done,
Please tell me what you think about the following line:
https://github.com/foxyproxy/browser-extension/blob/07202a4b68c8d2d5adb90d349e3c7693ef579d1a/src/_locales/en/messages.json#L101

**Comment by erosman** [comment]
> Please tell me what you think about the following line:

It might look better with a space e.g.

```
"fileSizeError": { "message": "پرونده با اندازهٔ بزرگتر از 1$ کیلوبایت مجاز نیست" },
```

In English, it would be, for example 8kb (no space for the abbreviation) or 8 kilobyte (space for the full word).

There is a typo:
```
"proxyList": { "message": "فهرسا پیشکار" },
```

Personally, I think some standard words should remain in English as their translation might be appropriate e.g. PAC, DNS. HTTP, HTTPS, URL etc
I also think `"extensionName" `should remain in English.
However, I will leave these for @ericjung  to decide on.

**Comment by ericjung** [comment]
Pleas do not translate the extension name, FoxyProxy.

**Comment by eshagh79** [comment]
Thank you for the points you said, I will correct them.
I rewrote the name of the program in Farsi, that is, it gives the same sound as English, I did not use the meaning of the words.
I and other translators usually do this to make the translation uniform.
About that few acronyms "PAC, DNS. "HTTP, HTTPS, URL, etc" in Farsi, there is a widely used equivalent for most of them, and for the rest, where there is no common translation, I use the same English word.

**Pull request merged**
